version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000lords
- name: bob
  coins:
  - 10000token
  - 100000000lords
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000lords
